repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.4  # use latest stable version
    hooks:
      - id: ruff
        args: ["."]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.15.0
    hooks:
      - id: pyupgrade
        args: ["--py39-plus"]
